### ISSUE TITLE
☂️ Consider making certain JNI routines leaf functions

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/native#1106]
For some of the routines, we can generate both the normal and the leaf versions, and call each one depending on the situation. For example `Set<PrimitiveType>ArrayRegion` could be fast depending on the length of the region, maybe it makes sense to conditionally call one or the other based on this.

Candidates:
- [x] `FindClass`
- [x] `DeleteGlobalRef`
- [x] `Get<Member>ID`
- [x] `GetStringLength`
- [x] `GetArrayLength`
- [x] `IsInstanceOf`
- [x] Primitive array operations
- [x] Direct byte buffer operations
- [ ] String methods – especially when https://github.com/dart-lang/sdk/issues/39787 is landed

For jnigen, users should be able to specify if a method is leaf or not, this can be done as a part of jnigen transformation. However simply:
- [x] Getting a field
- [x] Setting a field
Can be safely turned into leaf calls.

cc/ @dcharkes

**Comment by HosseinYousefi** [comment]
> For some of the routines, we can generate both the normal and the leaf versions, and call each one depending on the situation.

Regarding this, I don't have a clear guide on where to draw a line between a leaf functions and a non-leaf function, for example for array allocation, or `setRange`-like JNI methods. 

From a quick chat with @dcharkes: Running `dart --verbose-gc runtime/tests/vm/dart/gc/splay_test.dart` does ~67 GCs on an M1 machine. So limiting the time of a leaf function to ~1 ms means that we delay the GC about 1% of the time. So we could do some benchmarks for each function and see what is `N` where `f(N)` takes ~1ms. And maybe take `N / 10` as a cut-off to account for the performance differences of different machines.

Another option is to delegate the responsibility to the user by having two versions of each function, but I would still want to have good documentation in this case.

@rmacnak-google @mraleph @mkustermann @alexmarkov What is your take on this?

**Comment by dcharkes** [comment]
Not delaying GC for more than 1% is the longest-running we can aim for for making things leaf calls. Maybe typical usages are causing less GC than our splay_tree benchmark. Anyway if we want to be on the safe side: `100 us` on an M1.

We could also check what the shortest running time is for which marking it a leaf call still provides as significant performance benefit. For just summing two numbers it is a 3x speedup, but if a function is doing anything interesting, the run time of the function might dwarf the overhead of a non-leaf call anyway, in which case making it a leaf-call doesn't gain us much.

```
$ dart benchmarks/FfiCall/dart/FfiCall.dart 
FfiCall.Uint8x01(RunTime): 74.21317274823117 us.
FfiCall.Uint8x01Leaf(RunTime): 49.1377612881323 us.
FfiCall.Uint8x01Native(RunTime): 77.78375360923965 us.
FfiCall.Uint8x01NativeLeaf(RunTime): 34.90857473140215 us.
```

A leaf call with a single argument saves `25 us` - `40 us` on an M1 (if this benchmark correctly reports the time per call). So that would give us still a 10% performance gain for calls up to `400 us` on an M1.

So maybe if normal GC behavior is not as extreme as the splay_tree, we could consider setting the cutoff point at `0.5 ms` on an M1.

**Comment by HosseinYousefi** [comment]
For now I've decided not to make any of the potentially longer running functions into leaf calls. We can reopen/open another issue if someone has another idea.
