### ISSUE TITLE
[ffigen-objc] Trying to generate binding result in error.

### ISSUE THREAD

**Issue by famasf1** [dart-lang/native#1237]
Hi! I got a library written in Objective-C and I'm trying to bind it with Dart. I tried ffigen and some of the generated bindings have error `isn't in valid override`.

for instance, this code

```
@override
  NSMutableIndexSet initWithIndexesInRange_(NSRange range) {
    final _ret =
        _objc_msgSend_22(this.pointer, _sel_initWithIndexesInRange_, range);
    return NSMutableIndexSet.castFromPointer(_ret, retain: true, release: true);
  }
```

return this error

```
'NSMutableIndexSet.initWithIndexesInRange_' ('NSMutableIndexSet Function(_NSRange)') isn't a valid override of 'NSIndexSet.initWithIndexesInRange_' ('NSIndexSet Function(_NSRange)')
```

Or this one

```
  void postNotificationName_object_(
      DartNSNotificationName aName, objc.NSString? anObject) {
    _objc_msgSend_1112(this.pointer, _sel_postNotificationName_object_,
        aName.pointer, anObject?.pointer ?? ffi.nullptr);
  }
```

return this error

```
'NSDistributedNotificationCenter.postNotificationName_object_' ('void Function(NSString, NSString?)') isn't a valid override of 'NSNotificationCenter.postNotificationName_object_' ('void Function(NSString, NSObject?)').
```

I don't have strong knowledge on Objective-C itself so I have no idea what these errors are and how to fix them. But from a pure guesswork perspective, I presume this is because the library is using old API while `package:objective-c` implement a new API (the library I tried to generating from is 3+ years old.) But I'm not even sure on that one. Is it related to header file? If it help, I can post the original header file here. Thank you in advance for your assistance!

**Comment by liamappelbe** [comment]
This is a bug in ffigen/package:objective_c. The issue is that there's a copy of `_NSRange` in your generated bindings that is conflicting with the one in package:objective_c. The fix is to make the version in package:objective_c public so it can be reused by your bindings.

I fixed this in a [recent PR](https://github.com/dart-lang/native/pull/1175), but that version of the package isn't published yet. I'm hoping to publish 13.0.0 in the next couple of weeks, so you can wait for that.

If you don't want to wait, you can work around the issue by updating your config to filter out the class that contains that method (I recommend using the `exclude-all-by-default: true` option if you aren't already). If that doesn't work, you can just manually delete that method from the bindings. Not ideal, but a proper fix will be published soon.
