### ISSUE TITLE
[native_assets_cli] HookOutput dependencies should not have to include any Dart files

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#1256]
The compiler should know what Dart source files have been used running a Dart script. So we shouldn't request hook writers to list transitively all Dart files in `HookOutput.dependencies`.

Currently the hook is run as `dart path/to/some/hook/<hookname>.dart --config=path/to/config.json`.

In order to get a list of all Dart files used, we have multiple options:

1. Manually compiling to kernel first, and having that output a `.d` file (not preferred, I'd rather not depend on SDK internals.).
2. Adding a `--dependencies=path/to/deps.d` to `dart`. `dart --dependencies=path/to/deps.d path/to/some/hook/<hookname>.dart --config=path/to/config.json`. This could be used for other use cases as well. (preferred)

Then we can also get rid of the weird `dartBuildFiles` for the `CBuilder`:

```dart
        final cbuilder = CBuilder.library(
          sources: [addCUri.toFilePath()],
          name: name,
          assetName: name,
          pic: pic,
          dartBuildFiles: ['hook/build.dart'],
        );
```

Thanks @kustermann!

**Comment by dcharkes** [comment]
@jensjoha can the CFE output a list of dart source files?

**Comment by jensjoha** [comment]
The frontend_server for instance lists the keys in `component.uriToSource` (as in `+file1\n+file2` etc). Is that what you want? (I seem to be missing some context here).

**Comment by mkustermann** [comment]
We could even make `flutter build` and `dart build`:

* Figure out transitive package dependencies
* Find all the `N` `hook/*` scripts.
* Compile all of them to kernel: We could do that using P parallel incremental compilers that are given the `N` scripts to compile
* A compilation will emit kernel and a `.d` file containing dependencies
* We do the compilations in DFS order
* As soon as a kernel compilation has finished we can run it (assuming dependencies are ready)

Most of our tools already support emitting `.d` dependency files (e.g. `dart --snapshot-kind=kernel --snapshot=test.dill --depfile=test.dill.d test.dart`, frontend-server, dart2js, dart2wasm, ...) - because flutter already needs those dependency files to detect whether to rebuild things.

We should be really optimizing for compile times in `dart build ` / `flutter build`, e.g. if the package graphs depth is 30 and all of them use hooks, saving a single second (e.g. via parallel compile of hooks to kernel) would save half a minute for a developer.

**Comment by kustermann** [comment]
Guys, I’m not on your team!

Private and Confidential

Maximilian A. Kustermann
***@***.***
