### ISSUE TITLE
[jnigen] Use `String` instead of `Uri` everywhere

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/native#1371]

**Comment by dcharkes** [comment]
@HosseinYousefi Please contribute to the discussion https://github.com/dart-lang/native/issues/1506 if you care. 👌 Then we can align the packages. (Especially, when we start using the Dart instead of YAML config and we get a hook for running code-gens. Then we don't want to be converting between `File`/`Uri`/`String`.)

**Comment by HosseinYousefi** [comment]
I think using strings is simplest in the move to a dart config (instead of yaml).
