### ISSUE TITLE
Obj-C methods returning structs are generated incorrectly

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/native#1480]
The example I encountered is that `AVPlayer` has a method:

```objc
- (CMTime)currentTime;
```

This *should* (speaking as a client) generate:

```dart
CMTime currentTime()
```

but what it actually generates is
```dart
void currentTime(ffi.Pointer<CMTime> stret)
```

The fact that there is a parameter called `stret` is exposing *deep* Obj-C voodoo at the interface layer; I have *decades* of experience with Obj-C, am familiar with `objc_msgSend`, and still had to look this up to understand what I was looking at. `ffigen` should be abstracting away the out param dance and exposing it as a simple return value.

**Comment by liamappelbe** [comment]
This is working as intended, but I think we can improve it in more recent versions of Dart. Until recently there was no way of doing the equivalent of this in Dart FFI:

```C
// C code.
CMTime result;
currentTime(&result);
return result;
```

We would have had to `malloc` the `CMTime` struct, which is a difficult detail to hide. But now we have the [`StructAddress`](https://api.flutter.dev/flutter/dart-ffi/StructAddress.html) extension that can do this:

```Dart
// Dart code.
final result = CMTime();
currentTime(result.address);
return result;
```

Since it's only available in Dart 3.5, we'll either need a config flag for this, or bump the minimum SDK version.

@dcharkes Am I understanding `StructAddress` correctly?

**Comment by stuartmorgan** [comment]
Is there some reason the fallback can't be to copy the struct data into something returnable?

I don't think it's reasonable for the generated code to not match the API it's supposed to mirror, and to require such a deeply unidiomatic-for-Obj-C calling convention from clients. We cannot expect developers who know Dart and Obj-C to understand the pattern of manually mallocing memory for an out param.

**Comment by liamappelbe** [comment]
The solution using older FFI constructs is:

```Dart
final Pointer<CMTime> result = calloc<CMTime>();
currentTime(result);
return result;
```

But that's returning a `Pointer<CMTime>` instead of a `CMTime`, and the user has to know to free it when they're done.

A more heavyweight option would be to write a wrapper for `CMTime` that holds a `Pointer<CMTime>` and frees it automatically using finalizers. I guess we could make this generic and put it in `package:ffi`:

```Dart
class AllocatedPointer<T> implements Finalizable {
  final Pointer<T> ptr;
  AllocatedPointer<T>([Allocator alloc = calloc]) : ptr = alloc<T>() {
    // Set up finalizer to call alloc.free. Probably want to do this using
    // Dart_FinalizableHandle so AllocatedPointer can be sent between
    // isolates. Maybe factor out the shared parts of package:objective_c
    // and package:jni that do this sort of finalization.
  }
}
```

**Comment by dcharkes** [comment]
> Since it's only available in Dart 3.5, we'll either need a config flag for this, or bump the minimum SDK version.

We have always been bumping FFIgen to be targeting the latest stable version. So, using `.address` sgtm.

**Comment by stuartmorgan** [comment]
> The solution using older FFI constructs is:
> 
> ```dart
> final Pointer<CMTime> result = calloc<CMTime>();
> currentTime(result);
> return result;
> ```
> 
> But that's returning a `Pointer<CMTime>` instead of a `CMTime`, and the user has to know to free it when they're done.

I understand that; my question was why we can't rename that variable from `result` to `temp`, and then copy the data into a `final result = CMTime();`, and return that.

An extra struct copy would be much better than exposing the current API.

**Comment by liamappelbe** [comment]
> I understand that; my question was why we can't rename that variable from `result` to `temp`, and then copy the data into a `final result = CMTime();`, and return that (after freeing `temp`).
> 
> An extra struct copy would be much better than exposing the current API.

Good point. I hadn't considered that option. Still, as Daco points out, we can just bump the minimum Dart version to 3.5, and use `.address`.

**Comment by liamappelbe** [comment]
I ran into some problems implementing this, and now I'm remembering why I wrote it that way 😅. It'd be nice if this `.address` approach worked:

```Dart
// Version A
CMTime currentTime() {
  final result = CMTime();
  _objc_msgSend(result.address, this.ref.pointer, _sel);
  return result;
}
```

One issue that `struct.address` can only be used in a leaf call, and `msgSend` is not necessarily a leaf (99% of the time it will be, but it's possible it could invoke a callback that jumps back into Dart). I could avoid that issue by using Stuart's suggestion:

```Dart
// Version B
CMTime currentTime() {
  final ptr = calloc<CMTime>();
  _objc_msgSend(ptr, this.ref.pointer, _sel);
  final result = CMTime();
  result.field = ptr.ref.field;  // copy all fields...
  calloc.free(ptr);
  return result;
}
```

But the other issue is that structs can't be allocated like normal objects (The `final result = CMTime();` line gives an error). They have to be backed by native memory, so we have to store the data in a calloc'd pointer. We can return the struct by value, but it'd still have to be backed by a calloc'd pointer that someone has to free:

```Dart
// Version C
CMTime currentTime() {
  final ptr = calloc<CMTime>();
  _objc_msgSend(ptr, this.ref.pointer, _sel);
  return ptr.ref;  // Memory leak.
}
```

The simplest solution is probably to write a generic calloc'd struct pointer with a finalizer. @dcharkes would it make sense to add something like that to `package:ffi`? Something like my `AllocatedPointer` example above. It's better than taking a stret param, but still changes the signature a bit:

```Dart
// Version D
AllocatedPointer<CMTime> currentTime() {
  final ptr = AllocatedPointer<CMTime>();
  _objc_msgSend(ptr.pointer, this.ref.pointer, _sel);
  return ptr;
}
```

I guess another approach would be to add an option to ffigen to convert all structs into ordinary Dart classes with the same fields. That a much bigger change. Every time we pass a struct out of *or into* a method, we'd have to do this conversion dance where we calloc a pointer to the FFI struct and copy the fields across.

```Dart
// Version E
CMTime currentTime() {
  // _CMTime is an FFI struct. CMTime is an ordinary Dart class with the same fields.
  final ptr = calloc<_CMTime>();
  _objc_msgSend(ptr, this.ref.pointer, _sel);
  final result = CMTime();
  result.field = ptr.ref.field;  // copy all fields...
  calloc.free(ptr);
  return result;
}
```

Or better yet, the generated Dart object could internally own an `AllocatedPointer` to the backing struct, and instead of fields it could have getters/setters that delegate to the struct's fields.

```Dart
// Version F
CMTime currentTime() {
  // CMTime is an ordinary Dart class wrapping an AllocatedPointer<_CMTime>.
  final result = CMTime();
  _objc_msgSend(result.pointer, this.ref.pointer, _sel);
  return result;
}
```

So I guess the two viable options are D and F. D is a simple, lightweight change. F is a bigger change but is more ergonomic.

**Comment by dcharkes** [comment]
> calloc'd struct pointer with a finalizer.

Yes, you can

1. allocate the `Pointer` with `calloc`,
2. create a typed data out of it with a finalizer with https://api.flutter.dev/flutter/dart-ffi/Uint8Pointer/asTypedList.html
3. then use https://api.flutter.dev/flutter/dart-ffi/Struct/create.html to pass in the typed data,
4. and return that struct.

That would simply be straight-line code. No need for a `AllocatedPointer` I think.

**Comment by stuartmorgan** [comment]
> But the other issue is that structs can't be allocated like normal objects (The `final result = CMTime();` line gives an error).

What about `Struct.create()`?

**Comment by mkustermann** [comment]
> What about Struct.create()?

Those can be used in use cases where you need it by-value (pass or return). The only way to access it's `.address` is via calling a C leaf function (where we can hand out an inner pointer to Dart VM heap objects) - as mentioned by Liam further up.

**Comment by liamappelbe** [comment]
I wasn't aware of `Struct.create`. Thanks Daco and Stuart for pointing me to it. That would make version B feasible, and Daco has also outlined another `Struct.create` option that avoids the hassle of copying fields (sounds like it only does one allocation too, whereas version B with `Struct.create` would do 2).

```dart
// Version G
CMTime currentTime() {
  final ptr = calloc<CMTime>();
  final typedData = ptr.cast<Uint8>.asTypedData(sizeOf<CMTime>(), finalizer: calloc.free);
  // (can't actually directly pass calloc.free as the finalizer, need to load the native free function)
  final result = Struct.create<CMTime>(typedData);
  _objc_msgSend(ptr, this.ref.pointer, _sel);
  return result;
}
```

It's a bit convoluted, so I'll add a util for creating a struct like this, if I go with this approach.

@dcharkes Does the `result` struct keep the `typedData` alive?

**Comment by dcharkes** [comment]
> @dcharkes Does the `result` struct keep the `typedData` alive?

No it does not. So if `currentTime` from your example gets inlined and then the result is not used, the finalizer could potentially run too early. We don't actually need `result` to keep `typedData` alive. Instead we need to keep `typedData` alive until after `_objc_msgSend`. This can be easily by only making the typed data _after_ the FFI call.

> ```dart
> // (can't actually directly pass calloc.free as the finalizer, need to load the native free function)
> ```

How about `calloc.nativeFree`?
https://github.com/dart-lang/native/blob/c15b4b0187179dc73bc20a4125c501f0f7d9fbf7/pkgs/ffi/lib/src/allocation.dart#L218

```dart
// Version G
CMTime currentTime() {
  final ptr = calloc<CMTime>();
  _objc_msgSend(ptr, this.ref.pointer, _sel);
  final typedData = ptr.cast<Uint8>.asTypedData(sizeOf<CMTime>(), finalizer: calloc.nativeFree);
  final result = Struct.create<CMTime>(typedData);
  return result;
}
```

**Comment by stuartmorgan** [comment]
FYI, it looks like the `.asTypedData` needs to be `().asTypedList` in order to compile.

**Comment by liamappelbe** [comment]
> > @dcharkes Does the `result` struct keep the `typedData` alive?
> 
> No it does not. So if `currentTime` from your example gets inlined and then the result is not used, the finalizer could potentially run too early. We don't actually need `result` to keep `typedData` alive. Instead we need to keep `typedData` alive until after `_objc_msgSend`. This can be easily by only making the typed data _after_ the FFI call.

Hmmm. If `Struct.create` is essentially a view into the `TypedData`, but the struct doesn't keep the `TypedData` alive, then the `TypedData` could be GC'd before the struct, its finalizer would free the memory that backs the struct, and the struct would be pointing into invalid memory. If that's true, this approach isn't going to work. We're trying to return the struct, so it needs to outlive the whole function.

**Comment by dcharkes** [comment]
> > > @dcharkes Does the `result` struct keep the `typedData` alive?
> > 
> > 
> > No it does not. So if `currentTime` from your example gets inlined and then the result is not used, the finalizer could potentially run too early. We don't actually need `result` to keep `typedData` alive. Instead we need to keep `typedData` alive until after `_objc_msgSend`. This can be easily by only making the typed data _after_ the FFI call.
> 
> Hmmm. If `Struct.create` is essentially a view into the `TypedData`, but the struct doesn't keep the `TypedData` alive, then the `TypedData` could be GC'd before the struct, its finalizer would free the memory that backs the struct, and the struct would be pointing into invalid memory. If that's true, this approach isn't going to work. We're trying to return the struct, so it needs to outlive the whole function.

Any read of fields of the struct would keep the typed data alive. If the struct fields are never read, and the struct is never passed by value to an ffi call, it can be safely GCed. (Passing the struct by value should pulls out the backing typed data, so that should also keep it alive.)

During `_objc_msgSend(ptr` it would not be kept if you'd had created the typed data before that call. It's only safe to use `asTypedList` after you're done using `ptr`.
