### ISSUE TITLE
[ffigen] imported typedefs use `Foo` instead of `DartFoo` in Dart signatures

### ISSUE THREAD

**Issue by blaugold** [dart-lang/native#1776]
[Repro](https://github.com/blaugold/ffigen_enum_import_file_issue.git)

Given the following files:

```c
// a.h

#pragma once

typedef int Foo;
```

```c
// b.h

#pragma once

#include "a.h"

void bar(Foo foo);
```

`ffigen` generates these files:

```dart
// a.dart

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

typedef Foo = ffi.Int;
typedef DartFoo = int;
```

```dart
// b.dart

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;
import 'package:ffigen_enum_import_file_issue/a.dart' as imp1;

/// B
class B {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  B(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  B.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void bar(
    imp1.Foo foo,
  ) {
    return _bar(
      foo,
    );
  }

  late final _barPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(imp1.Foo)>>('bar');
  late final _bar = _barPtr.asFunction<void Function(imp1.Foo)>();
}
```

While in `_barPtr` `imp1.Foo` should be used, in `_bar` and `B.bar` `imp1.DartFoo` should be used.

**Comment by liamappelbe** [comment]
Looks like the symbol file infra needs to be made aware of the `Foo` vs `DartFoo` distinction. @mannprerak2 you wrote the symbol file stuff, do you want to take a look at this issue?

**Comment by liamappelbe** [comment]
> Probably the best course of action here would be to not put symbols that have a different C and Dart signature in the symbol file. Wdyt?

Can we make the symbol file aware of types with different C and Dart signatures? Instead of mapping from USR to type directly, it could map from USR to a little struct containing the dart type and the C type?

Better yet, only do that if the Dart type != the C type. If they're the same then it could keep the current approach. That would avoid bloating the symbol file, and also ensure backwards compatibility. I think that'd be the best user experience.

**Comment by mannprerak2** [comment]
Okay I may have forgotten a bit about all this, but is it not that only typedefs to native types (may be nested)  the only symbols that would have different C and Dart signatures? (like the one in the example above)

If that's true, there's no real point in sharing these types, since types are interchangeable (int == DartFoo).

Unless there are more such types (perhaps in Objective C?) then it makes sense to separate out C and dart symbols.

**Comment by liamappelbe** [comment]
Yeah, I think this might come up more often in ObjC. But even if we just focus on typedefs, I think it would be better for users if we do support them. It makes the generated APIs more readable.
