### ISSUE TITLE
Support `Iterable` on `JArray`

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/native#1792]
Converting a `JArray` to a `List`, or using it directly, is currently a much worse experience than Dart collections because of the lack of `Iterable` support. E.g., I had to write:

```dart
    final JArray<File?>? dirs = _appContext.getExternalCacheDirs();
    if (dirs == null) {
      return <String>[];
    }
    final List<String> paths = <String>[];
    for (int i = 0; i < dirs.length; ++i) {
      final String? path = dirs[i]?.getAbsolutePath()?.toDartString();
      if (path != null) {
        paths.add(path);
      }
    }
    return paths;
```

instead of what I would write if I were dealing with idiomatic Dart collections, which is something like:

```dart
    return _appContext.getExternalCacheDirs()
        ?.map((File? f) => f?.getAbsolutePath()?.toDartString())
        ?.nonNulls ?? <String>[];
```

(This is the `jnigen` equivalent of https://github.com/dart-lang/native/issues/1474)

**Comment by HosseinYousefi** [comment]
`JList<T>` is currently an iterable. The reason that `JArray<T>` is not is due to the fact that it can also be of primitive types like `JArray<jbyte>` so its `operator []` does not always return `T`, in case of `jbyte`, `jint`, ... it returns Dart `int`. The way it works is by having extension methods for each primitive type to have different operator `[]` and `[]=`. `Iterator<T>` for primitives would be `Iterator<jbyte>`, but we don't want `current` to return `jbyte`; we want it to return `int` as well.

In retrospect it's better to separate primitive arrays into their own classes instead of shoehorning them into being generics as well. So we could have `JIntArray`, JByteArray`, ... and `JArray<T extends JObject>`.

This is similar to what Kotlin does as well: https://kotlinlang.org/docs/java-interop.html#java-arrays
