### ISSUE TITLE
[native_assets_cli] `HookConfigBuilder.checksum` should exclude some keys

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#1803]
The refactoring in https://github.com/dart-lang/native/pull/1643 does a blanket checksum over the whole json representation of the config, this leads to the build-directory changing and cache disappearing for various config elements that should not have this effect:

* `linkConfig.assetsForLinking` https://github.com/dart-lang/native/pull/1746
* `config.codeConfig.cCompiler`
* `config.codeConfig.targetIOSVersion`, `.targetMacOSVersion`, `.targetAndroidNdkApi`

If any of these change, we're likely not interested in any previous invocations of the same hook with the previous versions. (Note for `config.codeConfig.targetIOSSdk` we _do_ actually want to cache the simulator and device separately, because you'd actually switch between building those in a Flutter project.)

I worked around `linkConfig.assetsForLinking` by applying `setupLinkConfig` after computing the hash, but that doesn't work for `setupCodeConfig`, because some parts should be taken into account for the hash while others don't.

Possible solutions:

1. Keep a `json` and a `jsonForChecksum`.
2. Keep a `listOfPathsForChecksum`

Side note, currently the checksum is dependent on the order in which the separate parts are added. This is a bug, the maps in the JSON should be regarded as inherently unsorted.

Possible solutions:

1. recursively sort before hashing
2. Use a hashing algorithm for sets

cc @mkustermann

**Comment by mkustermann** [comment]
> The refactoring in https://github.com/dart-lang/native/pull/1643 does a blanket checksum over the whole json  ... this leads to the build-directory changing and cache disappearing for various config elements that should not have this effect:

It should exclude the `out` / `out_shared` members I believe, doesn't it?

> cache disappearing for various config elements that should not have this effect:
> * `cCompilerConfig.*`

How often does the C compiler config change? Does it matter at all?

It's the safest thing to do to re-run the hook in a clean slate if the config (anything in the config modulo `out` / `out_shared`) changed. The hook doesn't even have to think about doing internal invalidation for things changing in the config. Imagine the hook would be invoked in the same directory but with different android api levels, then it would need to remember which one it used last time and basically invalidate bits and pieces that depend on api level. Seems complicated and error prone.

If there are expensive operations that one wants to cache across different configs, then users have the `out_shared` they can use for that. That's why we have it in the first place, no?

Also in the future, if we add metadata support (maybe it's still there?) we'd run it from clean state if metadata changed. If we don't do this, then again the hook itself needs to deal with this internally somehow, remember last metadata new metadata and magically know what needs to be invalidated.

Basically it's a trade-off of how much the system takes care of caching/invalidation vs the individual hooks. I think the way it's now is a reasonable sweet spot: For a typical developer they will `flutter run` many times and it will use the same config every time, so the system ensures to use same directory & developer gets incremental builds. And a hook author doesn't have to guard against being invoked in a "dirty" directory that matches a different configuration from a previous run and has to deal with that somehow.

> * `linkConfig.assetsForLinking`

This particular one we could explicitly exclude, yes. Currently it will only use a new directory if the set of assets changes (or the file uris in the assets), but not if the assets have different content.

Though as bugs like https://github.com/dart-lang/native/issues/1412 show reusing the same dir leads to bugs. So this is a "safer" solution.

I'm open to excluding that one.

> If any of these change, we're likely not interested in any previous invocations of the same hook with the previous versions.

Exactly, so we don't benefit from an old populated out directory (normally we benefit because we have an incremental build, but if api levels change we have to compile things from scratch anyway).

> Side note, currently the checksum is dependent on the order in which the separate parts are added. This is a bug, the maps in the JSON should be regarded as inherently unsorted.

That's not a bug as it causes no trouble. Also, a tool like flutter does generate them in a deterministic order (for same config it will always generate them in the same order and the checksum will therefore be the same) - only if the flutter SDK was updated may it change the order, which isn't a problem.

If we want to keep it sorted (and we really don't have to) we should do it in one place instead of assuming N different places in the codebase happen to remember to sort the maps, I've filed https://github.com/dart-lang/native/issues/1650 for this some time ago.

> Possible solutions:
>
> Keep a json and a jsonForChecksum.
> Keep a listOfPathsForChecksum

Or leave it like it is :)

> Possible solutions:
>
> recursively sort before hashing
> Use a hashing algorithm for sets

Or leave it like it is :)

**Comment by dcharkes** [comment]
> That being said, I am a little concerned of us creating lots of directories that users eventually need to `rm -rf` because they run out of space.

That would be a second benefit of including less of the JSON into the checksum indeed.

Presumably, the asset-specific-config-provider would know which parts of the config would cause unnecessary creation of new output directors. But I'm not entirely convinced of this yet.

> It's actually an ordered collection not an unordered collection

(Right, we don't have the equivalent of `unordered_map`, which does not allow us to express precisely what we care about. We're over-specifying.)
