### ISSUE TITLE
[Feature] Config to expose unused `typedef`s

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/native#320]
dart-lang/ffigen#224 generates only the required typedefs, which results in hacks like this:

https://github.com/Sunbreak/dynamic_load.trial/blob/56953bb6e0b5d4badffb13bf3446cd794c914d26/example/ntdll/winternl.dart#L20

```dart
// FIXME: https://github.com/dart-lang/native/issues/320
abstract class SYSTEM_INFORMATION_CLASS {
}

class SYSTEM_PROCESS_INFORMATION extends ffi.Struct {
}
```

---

`SYSTEM_INFORMATION_CLASS` and `SYSTEM_PROCESS_INFORMATION` is a usecase for https://github.com/dart-lang/native/issues/359

**Comment by rainyl** [comment]
This feature is also useful when we want to split wrapper type definitions and functions or split the generated bindings to different files when the project becomes complicate and large.

e.g., 
```C
// types.h
typedef void *SomeClassA;
typedef void *SomeClassB;
typedef void (*Callback)(void *);
...and many other similar typedefs.
```

then if we just generate this file, all typedefs will not be generated because they are not used.

I know that you may want to say: just include it in the headers that use it!

e.g.,
```C
// moduleA.h
#include "types.h"

// return value is a status code
int create_A(Callback callback);
int A_getB(SomeClassA self, Callback callback);
````

```C++
// moduleA.cpp
#include "moduleA.h"

int create_A(Callback callback){
  callback(new SomeClassA());
  return 0;
}

int A_getB(SomeClassA self, Callback callback){
  SomeClassB *b = self->getB();  // here, since SomeClassB doesn't appear in moduleA.h, it will not be generated.
  callback(b);
  return 0;
}
```

Yes it works, but still, only those used in func.h (`SomeClassA`) will be included, it will be annoying to use `A_getB` since `SomeClassB` is not generated.

The above is just a simple usage, if we want to split the bindings to different modules, it will be better to also generate unused typedefs such as `SomeClassB`, so we can just import the generated `moduleA.generated.dart` to use `SomeClassB` instead of import another `types.generated.dart` to access `SomeClassB`.
