### ISSUE TITLE
Move core ObjC classes into their own library

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/native#430]
For example `NSObject` and `NSString`. This makes sense from a modularisation perspective, and also solves the problem where 2 different code genned ObjC libraries are incompatible.

**Comment by liamappelbe** [comment]
I'm starting work on this now. Gonna call it `package:ffigen_objc`, unless anyone objects.

**Comment by dcharkes** [comment]
> I'm starting work on this now. Gonna call it `package:ffigen_objc`, unless anyone objects.

How about:

* `package:ffi_objc` or `package:ffi_objectivec` or `package:ffi_objective_c`? It's a helper package that doesn't do any generation but is targetted by code gen. It's like the helpers in `package:ffi` and `package:jni` but for the context Objective-C.
* (`package:objective_c`. I like this slightly less, because it does not refer to FFI in any way. E.g. it could be a package that generates Objective-C instead of that interops with Objective-C.)

I don't see many guidelines for package names (besides https://dart.dev/tools/linter-rules/package_names).

cc @mit-mit @jonasfj @lrhn for package name

**Comment by lrhn** [comment]
How will the package be imported? Will the user have to import it, or will `ffi_gen` inject an import?
(In the latter case, the user still needs a non-dev dependency on the package.)

Could it be a separate libraries of `package:ffi`, as `package:ffi/objective_c.dart`. If nothing else, the user presumably has a dependency on `package:ffi` already. (The title says "its own library", not "its own package", so ....?)

**Comment by dcharkes** [comment]
> How will the package be imported? Will the user have to import it, or will `ffi_gen` inject an import? (In the latter case, the user still needs a non-dev dependency on the package.)

The latter. (It is similar to `package:jni`, the generated code will import it.)

> Could it be a separate libraries of `package:ffi`, as `package:ffi/objective_c.dart`. If nothing else, the user presumably has a dependency on `package:ffi` already. (The title says "its own library", not "its own package", so ....?)

It could. However, I am slightly worried about breaking changes. Objective C support is still experimental. `package:ffi` is used all over the place, and users are already using dependency overrides because they have dependencies using v1.x.x and v2.x.x. I'd like to avoid having to bump `package:ffi`'s major version because we update `package:ffi/objective_c.dart` in a breaking way. @liamappelbe Do you expect us to do breaking changes to `package:ffi_objective_c` while iterating on it?

**Comment by lrhn** [comment]
> The latter. (It is similar to `package:jni`, the generated code will import it.)

Which means that the code using `ffi_gen` needs to have a non-dep dependency on the package.

In that case, I think it's *better* to put the files inside `package:ffi` and only have one package dependency.

The breaking change for experimental code is an issue, but that should end eventually. Could you just mark the library as `@experimental`, and break it with abandon?

If we expect breaking changes *post* experiment stage, then linking things that evolve independently is an issue, since it can introduce too many major-version increments. Then separate packages is probably the right thing.

In that case, I'd go with `package:ffi_objective_c` if the package cannot be used directly, only through `ffi_gen`.
If it can be used directly as well, then `package:objective_c` is fine.
(Can `package:jni` be used by itself, or should it be called `package:ffi_jni`?)

**Comment by HosseinYousefi** [comment]
> Gonna call it `package:ffigen_objc`, unless anyone objects.

Having `gen` in the name might suggest that it is a code generator. 

> If we expect breaking changes post experiment stage.

I would personally expect that based on my experience.

> (Can `package:jni` be used by itself, or should it be called `package:ffi_jni`?)

It can be used by itself. We have a `package:jni/internal_helpers_for_jnigen.dart` as well (I know, long name, but I kept it the way it was!) that exposes certain functionalities that only `package:jnigen` needs.

The thing about `package:jni` is that we might decide to decouple it from some future `package:java_core` and `package:kotlin_something`. Where `package:jni` only has the very basic classes like `JReference` and `JObject` and all the other classes exist in a different package. But again it's a good default for `jnigen` and `ffigen` to use the classes inside `package:java_core` by default.

> JNI is already "Java native interface", so it is inherently FFI related.

Am I the only one who doesn't really mind not directly implying the fact that these packages are `ffi` related in the name?

**Comment by liamappelbe** [comment]
> @liamappelbe Do you expect us to do breaking changes to `package:ffi_objective_c` while iterating on it?

Definitely. My experience has been that generated code changes more often and more drastically than normal code.

Based on everyone's feedback, I'm leaning towards `package:ffi_objc`.

**Comment by dcharkes** [comment]
> > @liamappelbe Do you expect us to do breaking changes to `package:ffi_objective_c` while iterating on it?
> 
> Definitely. My experience has been that generated code changes more often and more drastically than normal code.

👍 

> Based on everyone's feedback, I'm leaning towards `package:ffi_objc`.

I'd prefer `package:ffi_objective_c`, because I believe it would be better to avoid abbreviations. (Although, we do have ffi**gen** where generator is abbreviated to gen. So maybe this isn't the strongest argument. 😆)

**Comment by HosseinYousefi** [comment]
> > > @liamappelbe Do you expect us to do breaking changes to `package:ffi_objective_c` while iterating on it?
> > 
> > 
> > Definitely. My experience has been that generated code changes more often and more drastically than normal code.
> 
> 👍
> 
> > Based on everyone's feedback, I'm leaning towards `package:ffi_objc`.
> 
> I'd prefer `package:ffi_objective_c`, because I believe it would be better to avoid abbreviations. (Although, we do have ffi**gen** where generator is abbreviated to gen. So maybe this isn't the strongest argument. 😆) Happy with either of the two.

I like `package:objective_c`.

As @lrhn said: 
> If it can be used directly as well, then package:objective_c is fine.

And I think it _can_ be used directly.

**Comment by liamappelbe** [comment]
> And I think it _can_ be used directly.

Fair enough. @dcharkes any objections to `package:objective_c`? I would prefer `package:objc`, but I don't think I'm going to win that argument 😛

**Comment by dcharkes** [comment]
> > And I think it _can_ be used directly.
> 
> Fair enough. @dcharkes any objections to `package:objective_c`? I would prefer `package:objc`, but I don't think I'm going to win that argument 😛

sgtm!
