### ISSUE TITLE
How to implement a custom `Builder`?

### ISSUE THREAD

**Issue by TENX-S** [dart-lang/native#867]
I'm working on integrating native Golang code into my Flutter app through dynamic libraries and the native-assets feature. While ffigen served my initial needs, I now aim to merge Dart(generated by ffigen) and Golang code into a single package.

To achieve this, I recognized the necessity of implementing the `Builder` protocol. There is only `CBuilder` available. So I'm developing my `GoBuilder` to execute the equivalent of `go build -buildmode=c-shared -o ${outDir}/libMyPackage.dylib` during the `GoBuilder.run` process. The resulting `build_output.yaml` file in the 'out' directory should also be generated accurately.

Despite my efforts, I've found minimal documentation on the `Builder` protocol and no guidance on custom `Builder` implementation. Any assistance or insights on this matter would be greatly appreciated.

P.S. `go build -buildmode=c-shared -o ${outDir}/libMyPackage.dylib` will also generate a C header file which is the `entry-points` for the ffigen runner.

**Comment by dcharkes** [comment]
Hi @TENX-S!

It would be very cool to have a Go Builder indeed!

I haven't spend much thought yet on what would be a programmatic good API to do this.

For now, you should rely on consuming `BuildConfig` for the information you need, and populating a `BuildOutput` with the dylibs produced and the files read. (In the future it might be worthwhile creating a nice API for both the CBuilder and GoBuilder.)

For discovering the Go compiler, you could either rely on the user providing `go` on the path, and otherwise failing the build (`build.dart` should return non-zero exit code, for example by `exit(1);` or an uncaught exception). Or you could reuse the tools abstraction in this repo.

You could provide the GoBuilder in a separate package that imports `package:native_assets_cli`.

We haven't hammered out the details for `package:native_assets_cli` yet. Sorry for the lacking documentation. And also sorry that we're likely going to break it in the future when we come up with a nicer API. 🙈  Any feedback on what the API should look like is welcome!

Did you have specific questions about what should go in the `build_output.yaml`?

Maybe you can take some inspiration from https://github.com/dart-lang/native/tree/rust-example, it does exactly what you want but then for Rust.  (And it also generates a C header file which is the entry-points for the FFIgen runner.)

**Comment by dcharkes** [comment]
The script looks good.

> Yes! What does the `dependencies` field mean? I noticed that in the `build_output.yaml` of the `native_assets_cli/example` compilation output, the `dependencies` field includes the absolute paths of `native_add_library/build.dart` and `native_add_library.c`. My assumption is that these paths are intended for Dart or Flutter usage, and that when these files change, the C file will be recompiled.

Correct, that list of files is used to invalidate the build cache.

**Comment by TENX-S** [comment]
Thank you for the help here! Feel free to close this issue at your discretion. `native-assets` is a exciting feature, can't wait to see it in the stable channel. Keep up the good work!
