### ISSUE TITLE
[ffigen] generate header files for swift code using `swiftc`

### ISSUE THREAD

**Issue by wurikiji** [dart-lang/native#892]
I am using the command below to generate the `.h` header file for my swift code.  But if the swift code contains the `import Flutter,` it fails with `no such module Flutter.` But when I open the iOS project with XCode, there are no warnings or errors about the flutter module. 

```sh
swiftc -c ios/Runner/managed_settings.swift -module-name Runner -emit-objc-header-path ios/managed_settings.h -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -target arm64-apple-ios16.0
```

I tried 
- remove ios folder and regenerate using `flutter create`
- `flutter clean` and then `flutter pub get`
- clean the project `pod install` and then `pod update`

and other solutions I found from the issues, but none of them solved the problem.

Is there any solution for this?

**Comment by dcharkes** [comment]
This seems more of a question about Swift than about Dart.

Maybe @liamappelbe knows the answer to this.

**Comment by liamappelbe** [comment]
I don't have a lot of experience with swift, but if the compiler is anything like clang you'll need to tell it to import the Flutter framework/module somehow.

There's probably a flag you can pass to swiftc. Unfortunately, there's hardly any documentation for the swiftc compiler, because Apple expects you to just use xcode. It's hard to even find a list of flags, so when I was first figuring out the swift workflow this I used [this list](https://github.com/apple/swift/blob/main/include/swift/Option/FrontendOptions.td). The `import_module` flag looks promising.

Another possibility is that swiftc could be searching for a file that specifies the deps, similar to Dart's pubspec file. I've seen mentions of a modulemap file in my googling, so maybe your flutter project has a modulemap file somewhere, and you just need to point swiftc at that file?
