### ISSUE TITLE
Converting char* to dart string

### ISSUE THREAD

**Issue by Ben1980** [dart-lang/native#936]
I'm trying to wrap an oss library which has an opaque struct. the struct is taken as an argument to `void*`. The function itself is returning 0 which means everything went well but the cast to a dart string is ending up in a `Missing extension byte (at offset ...)` exception. I try something similar also in a simplified example but there it works well [minimal example](https://github.com/Ben1980/ffiexample/blob/main/lib/ffigen_app.dart), [simple c function](https://github.com/Ben1980/ffiexample/blob/main/src/test.c).
The header file:
```
/**
 * Opaque object representing a supported dive computer.
 */
typedef struct dc_descriptor_t dc_descriptor_t;

dc_status_t
dc_iterator_next (dc_iterator_t *iterator, void *item);
```
The source file:
```
struct dc_descriptor_t {
	const char *vendor;
	const char *product;
	dc_family_t type;
	unsigned int model;
	unsigned int transports;
	dc_filter_t filter;
};

dc_status_t
dc_iterator_next (dc_iterator_t *iterator, void *item)
{
	if (iterator == NULL || iterator->vtable->next == NULL)
		return DC_STATUS_UNSUPPORTED;

	if (item == NULL)
		return DC_STATUS_INVALIDARGS;

	return iterator->vtable->next (iterator, item);
}
```
My calling code looks like the following:
```
final class DcDescriptorT extends Struct {
  external Pointer<Char> vendor;
  external Pointer<Char> product;
  @Int32()
  external int type;
  @Int32()
  external int model;
  @Int32()
  external int transports;
  external Pointer<NativeFunction<DcFilterT>> filter;

  DcDescriptorT() {
    vendor = calloc<Char>();
    product = calloc<Char>();
  }
}

Pointer<dc_descriptor_t> descriptor = calloc<DcDescriptorT>().cast<dc_descriptor_t>();
inal status =  _bindings.dc_iterator_next(iterator.value, descriptor.cast<Void>());
final vname = vendor.cast<Utf8>().toDartString();
```

**Comment by mraleph** [comment]
I have explained on Discord that the problem is that APIs are not used correctly. @Ben1980 needs to look at man pages and then transcribe C code to Dart mapping constructs appropriately. They key is to first understand how C code using the API would look like and then write corresponding Dart code.

If you see an opaque struct in the C header then obviously C code would not be able to allocate it to invoke the API - so you should not try that either. 

Let us look at the [man page](https://github.com/libdivecomputer/libdivecomputer/blob/de6696bc7fb4d129ba9be6175a684c53a2b8c659/doc/man/dc_descriptor_iterator.3#L22). We see the following code there:

```cpp
while (dc_iterator_next(iter, &desc) == DC_STATUS_SUCCESS) {
	printf("%s\en", dc_descriptor_get_vendor(desc));
	dc_descriptor_free(desc);
}
```

It omits declaration of `desc` - which I admit can be confusing, but from the flow of the code (because `desc` is later used in `dc_descriptor_get_vendor` and `dc_descriptor_free`) it is obvious that declaration would be `dc_descriptor_t* desc`.

This code needs to be translated to Dart, for example:

```dart
final descPtr = calloc<Pointer<dc_descritor_t>>();  // equivalent of &desc

while (_bindings.dc_iterator_next(iterator.value, descPtr.cast<Void>()) == DC_STATUS_SUCCESS) {
  final desc = descPtr.value;
  print(_bindings.dc_descriptor_get_vendor(desc).cast<Utf8>().toDartString());
  _bindings.dc_descriptor_free(desc);
}

calloc.free(descPtr);
```
