### ISSUE TITLE
[native_assets_builder] build input and output should be JSON instead of YAML

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#991]
@jonasfj and @mkustermann have pestered me enough about not using YAML for machine generated files. 😅 

Good arguments to switch to JSON:

* Less ambiguities in the format that we have to deal with.
* Less dependencies in `package:native_assets_cli` (get rid of the yaml_edit package dependency).

Inconvenience to switch to JSON from YAML:

* Trouble shooting user problems and developing will require parsing JSON files as a human being.

Least breaking way to go to JSON:

* Keep supporting both YAML and JSON for the time being.
* Keep supporting both the JSON and YAML file path for build output for the time being.
  * (Side note: @jonasfj Suggested we should not write the build output file to the output directory, so that it doesn't conflict with a possible asset file name.)
    * (Side side note: @mkustermann suggested we might use different output directories for different asset types e.g. the dylibs go in to a different dir than jars. I'm not sure if that gains us anything.)

**Comment by mkustermann** [comment]
> (Side side note: @mkustermann suggested we might use different output directories for different asset types e.g. the dylibs go in to a different dir than jars. I'm not sure if that gains us anything.)

By separating different asset types as sub-configs in config (e.g. `config.native`, `config.java`) and output (`output.java`, `output.native`) they are somewhat isolated from each other (which they should be, because adding native libraries vs jars is completely separate).

That in return means any sub-config may configure things like architecture, jdk versions, and they *could* also specify out directory - not saying that this is what we should do, but the structure would allow it.
